- name: Fetch RPI list from OpenVPN
  ansible.builtin.import_playbook: fetch_openvpn_hosts.yml
- name: Fetch RPI status information
  hosts: rpi
  gather_facts: no
  connection: ssh
  vars:
    ansible_remote_tmp: /run/user/1000
    pushbullet_api_key: "{{ lookup('ansible.builtin.env', 'PUSHBULLET_API_KEY') }}"
  tasks:
    - name: Fetch hostname and eth0 mac
      ansible.builtin.shell: |
        cat /etc/hosts | grep 127.0.1.1 | awk '{print $2}'
        /usr/sbin/ifconfig eth0 2>/dev/null|awk '/ether/ {print $2}'
        /usr/bin/python3 -c "from pijuice import PiJuice;import json;pijuice = PiJuice(1, 0x14);print(json.dumps({'status': pijuice.status.GetStatus(), 'battery': dict(pijuice.status.GetBatteryVoltage())}, indent=2))"
      register: rpi_host
    - name: Print result
      ansible.builtin.debug:
        msg: Raspberry Pi {{rpi_host.stdout}}
    - name: Fetch hostname and eth0 mac
      expected_string: '"powerInput": "PRESENT"'
      ansible.builtin.shell: /usr/sbin/ifconfig eth0 2>/dev/null|awk '/ether/ {print $2}'
      register: hwa
      when: rpi_host.stdout.find(expected_string) > -1
    - name: Alert if 5V usb not plugged in
      vars:
        expected_string: '"powerInput": "PRESENT"'
        ansible_remote_tmp: /tmp/ansible
      ansible.builtin.uri:
        url: https://api.pushbullet.com/v2/pushes
        method: POST
        body_format: "json"
        body: "{ \"hwa\": \"{{ hwa.stdout }}\" }"
        headers:
          Access-Token: "{{ pushbullet_api_key }}"
      delegate_to: localhost
      when: rpi_host.stdout.find(expected_string) > -1
